
// Cards
 var cards = [ {
 	rank:"queen",
 	suit:"clubs",
 	cardImage:"images/cards/queen-of-clubs.png",
 },
 {
 	rank:"queen",
 	suit:"spades",
 	cardImage:"images/cards/queen-of-spades.png",
 },
 {
 	rank:"king",
 	suit:"clubs",
 	cardImage:"images/cards/king-of-clubs.png",
 },
 {
 	rank:"king",
 	suit:"spades",
 	cardImage:"images/cards/king-of-spades.png",
 },
 {
	rank:"jack",
 	suit:"clubs",
 	cardImage:"images/cards/jack-of-clubs.png",
 },
 {
 	rank:"jack",
 	suit:"spades",
 	cardImage:"images/cards/jack-of-spades.png",
 },
 {
	rank:"10",
 	suit:"clubs",
 	cardImage:"images/cards/10-of-clubs.png",
 },
 {
	rank:"10",
 	suit:"spades",
 	cardImage:"images/cards/10-of-spades.png",
 },
 {
	rank:"9",
 	suit:"clubs",
 	cardImage:"images/cards/9-of-clubs.png",
 },
 {
	rank:"9",
 	suit:"spades",
 	cardImage:"images/cards/9-of-spades.png",
 },
 {
	rank:"8",
 	suit:"clubs",
 	cardImage:"images/cards/8-of-clubs.png",
 },
 {
	rank:"8",
 	suit:"spades",
 	cardImage:"images/cards/8-of-spades.png",
 },
 {
	rank:"7",
 	suit:"clubs",
 	cardImage:"images/cards/7-of-clubs.png",
 },
 {
	rank:"7",
 	suit:"spades",
 	cardImage:"images/cards/7-of-spades.png",
 },
 {
	rank:"6",
 	suit:"clubs",
 	cardImage:"images/cards/6-of-clubs.png",
 },
 {
	rank:"6",
 	suit:"spades",
 	cardImage:"images/cards/6-of-spades.png",
 },
 {
	rank:"5",
 	suit:"spades",
 	cardImage:"images/cards/5-of-spades.png",
 },
 {
	rank:"5",
 	suit:"clubs",
 	cardImage:"images/cards/5-of-clubs.png",
 }
 ];
